baseURL = "altinndigital.no"
languageCode = "nb"
defaultContentLanguage = "nb"

contentDir = "content"
staticDir = "static"
publishDir = "public"

title = "Altinn Digitalisering"
theme = "hugo-theme-altinndigital"
metadataFormat = "yaml"
pluralizeListTitles = false
preservetaxonomynames = true
enableEmoji = true
enableGitInfo = false
disableKinds = ["RSS"] # page home section taxonomy taxonomyTerm RSS sitemap robotsTXT 404

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "dracula" 

[markup.tableOfContents]
startLevel = 2
endLevel = 2
ordered = false

[blackfriday]
fractions = false # disable automatic fraction rendering

[params]
editURL = "https://github.com/Altinn/altinndigital.no"
noHomeIcon = true # default is false
noSearch = false # default is false
disableNavChevron = false
showVisitedLinks = false # default is false
# themeVariant = "default"


[outputs]
home = ["HTML", "JSON"] # JSON generates index.json file used by search
